test 5

diff --git a/.github/workflows/laravel.yml b/.github/workflows/laravel.yml
--- a/.github/workflows/laravel.yml
+++ b/.github/workflows/laravel.yml
@@ -28,17 +28,22 @@ jobs:
         # SSH into VPS
         sshpass -p $PASS ssh -o StrictHostKeyChecking=no $VPS_USER@$VPS_IP << EOF
 
-          # Navigate to deployment directory
-          cd /home/$VPS_USER/laravel_app || exit
+          # Navigate to the home directory
+          cd /home/$VPS_USER || exit
 
-          # Stop and remove old containers if they exist
-          docker-compose down || true 
+          # Check if laravel_app directory exists, if yes, clean up
+          if [ -d "/home/$VPS_USER/laravel_app" ]; then
+            cd laravel_app || exit
 
-          # Clean up cloned repository
-          cd ..
-          rm -rf laravel_app
-          
-          # Clone the repository
+            # Stop and remove old containers if they exist
+            docker-compose down || true 
+
+            # Clean up old cloned repository
+            cd ..
+            rm -rf laravel_app
+          fi
+
+          # Clone the repository into the laravel_app directory
           git clone https://github.com/Quaniscoding/Library-management.git /home/$VPS_USER/laravel_app
 
           # Navigate to the Laravel app directory
@@ -48,14 +53,10 @@ jobs:
           docker-compose up -d --build
 
           # Run database migrations and seeds
-          # docker-compose exec app php artisan migrate --force
-          # docker-compose exec app php artisan db:seed --force
-
           sudo docker-compose exec app php artisan migrate --force
           sudo docker-compose exec app php artisan db:seed
 
-      
-
           # Clean up old Docker images
           docker image prune -f
+          
         EOF
